### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by jimmywarting** [apple502j/xhr-shim#1]
Why not just recommend to switch to using the fetch api instead?

**Comment by ohager** [comment]
Because you may use 3rd party libs which comes with XMLHttpRequests, or axios

**Comment by apple502j** [comment]
Just a hobby project but seems like some folks found a use :)

**Comment by cyan-2048** [comment]
why? because on KaiOS 2.5, to get rid of all restrictions you're supposed to use XHR even though there's fetch

**Comment by jimmywarting** [comment]
What kind of restrictions?

**Comment by cyan-2048** [comment]
> What kind of restrictions?

fetch/xhr in a normal web context, you're restricted with the following:
1. Setting certain request headers (cookie, User-Agent, etc.)
2. CORs

Yeah that's all I can think about, there's probably more.

On KaiOS 2.5 you can bypass all the restrictions by doing `new XMLHttpRequest({ mozSystem: true })`

It's a bit hard to find/create something that would work for both nodejs and KaiOS, so yeah this repo really helped...

Even tried axios, but have no idea why it creates an error.

**Comment by camhart** [comment]
Why--I want to use libraries that use XMLHttpRequest in a service worker.
